<?php

namespace DoctrineORMModule\Proxy\__CG__\Eventius\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evento extends \Eventius\Entity\Evento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nombre', 'slug', 'lugar', 'code', 'inicio', 'fin', 'organizador', 'fecha_creacion', 'fecha_modificado', 'estado', 'cierre', 'usuario_c', 'usuario_m');
        }

        return array('__isInitialized__', 'id', 'nombre', 'slug', 'lugar', 'code', 'inicio', 'fin', 'organizador', 'fecha_creacion', 'fecha_modificado', 'estado', 'cierre', 'usuario_c', 'usuario_m');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', array());

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', array($nombre));

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', array());

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', array($slug));

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugar', array());

        return parent::getLugar();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugar($lugar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugar', array($lugar));

        return parent::setLugar($lugar);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInicio', array());

        return parent::getInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setInicio($inicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInicio', array($inicio));

        return parent::setInicio($inicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFin', array());

        return parent::getFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setFin($fin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFin', array($fin));

        return parent::setFin($fin);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrganizador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrganizador', array());

        return parent::getOrganizador();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrganizador($organizador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrganizador', array($organizador));

        return parent::setOrganizador($organizador);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', array());

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechacreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', array($fechacreacion));

        return parent::setFechaCreacion($fechacreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaModificado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaModificado', array());

        return parent::getFechaModificado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaModificado($fechamodificado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaModificado', array($fechamodificado));

        return parent::setFechaModificado($fechamodificado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getCierre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCierre', array());

        return parent::getCierre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCierre($cierre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCierre', array($cierre));

        return parent::setCierre($cierre);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioC', array());

        return parent::getUsuarioC();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioC($usuario_c)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioC', array($usuario_c));

        return parent::setUsuarioC($usuario_c);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioM()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioM', array());

        return parent::getUsuarioM();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioM($usuario_m)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioM', array($usuario_m));

        return parent::setUsuarioM($usuario_m);
    }

}
