<?php 
use Zend\Mvc\Controller\Plugin\FlashMessenger;

$flashMessenger = new FlashMessenger();echo $this->doctype(); 
?>
<html lang="es">
    <head>

        <meta charset="utf-8">
        <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
        <?php echo $this->headTitle('Puntos de Cultura ' . $this->translate('Inscripción'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
               
                ->appendStylesheet($this->basePath() . '/fuelux/css/fuelux.min.css')
                ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                ->appendStylesheet($this->basePath() . '/css/bootstrap-select.min.css')
                ->appendStylesheet($this->basePath() . '/css/style.css')
                 //->appendStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                //->appendStylesheet($this->basePath() . '/css/theme.css')
                ;
        ?>



        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->appendFile($this->basePath() . '/js/jquery.min.js')
                ->appendFile($this->basePath() . '/inputmask/jquery.inputmask.bundle.js')
                
                //->appendFile($this->basePath() . '/js/jquery.validate.min.js')
                ->appendFile($this->basePath() . '/js/bootstrap.min.js')
                ->appendFile($this->basePath() . '/js/bootstrap-select.min.js')
                ->appendFile($this->basePath() . '/js/i18n/defaults-es_CL.js')
                ->appendFile($this->basePath() . '/fuelux/js/fuelux.min.js')
                ->appendFile($this->basePath() . '/fuelux/js/wizard.js')
                ->appendFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->appendFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))


        ;
        ?>

    </head>
    <body class="fuelux">
        <header>
            <div id="header">
                <div class="container">
                    <a class="logo navbar-brand" href="/">
                        <img class="img-responsive" alt="" width="260" src="/img/logo-cultura-nacion.png">
                    </a></div></div></header>
        <nav class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Formularios') ?></a> -->
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <?php  if ($this->zfcUserIdentity()) { ?>
                        <li ><a href="<?php echo $this->url('r',array('action'=>'registro')) ?>"><?php echo $this->translate('Formulario') ?></a></li>
                        <li ><a href="<?php echo $this->url('r',array('action'=>'listado')) ?>"><?php echo $this->translate('Listar') ?></a></li>
                        <?php  } else {?>
                        <li ><a href="<?php echo $this->url('home',array('action'=>'index')) ?>"><?php echo $this->translate('Registrar punto de cultura') ?></a></li>
                        <?php  } ?>
                        
                    </ul>
                    
       <ul class="nav navbar-nav pull-right ">
			<?php  if ($this->zfcUserIdentity()) { ?>
       
       
			<li>
				<a data-toggle="dropdown" class="dropdown-toggle" href="#">
	            <span class="glyphicon glyphicon-user"></span>
	           	<?php echo $this->zfcUserDisplayName() ?>
	           	<b class="caret"></b></a>
				<ul class="dropdown-menu">
					 <li><a href="<?php echo $this->url('zfcuser/perfil') ?>">Perfil</a></li>
		   		     <li class="divider"></li>
		   			 <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><span class="glyphicon glyphicon-off"></span> Cerrar sesión</a></li>
		 		 </ul>
			</li><?php } else { ?>
                            <li ><a href="<?php echo $this->url('r',array('action'=>'index')) ?>"><?php echo $this->translate('Alertas') ?></a></li>
                        
                            <?php } ?>
		</ul>
		
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
            <?php 
    if ($flashMessenger->hasMessages()) {
        foreach ($flashMessenger->getMessages() as $flashMessage) {
            $parte = explode("_", $flashMessage);
            echo $this->ztbAlert($parte[1], TRUE, 'alert-' . $parte[0]);
        }
        $flashMessenger->clearMessages();
    }
    ?>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>Ministerio de Cultura</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
<script type="text/javascript">
	//$(document).ready(function() {
	//$(".fancybox").fancybox();
	//});
        
        var MyDialogs={
    loadConfirmationModal:function(modalId, confirmURL, caption, body, footer){
                        var $modal=jQuery('#'+modalId);
                        if($modal.size() === 0){

			var modalString='<div id="'+modalId+'" class="modal">'+
								'<div class="modal-dialog">'+
									'<div class="modal-content">'+
                                        '<div class="modal-header">'+
                                                '<button class="close" data-dismiss="modal">×</button>'+
                                                '<h3>'+caption+'</h3>'+
                                        '</div>'+
                                        '<div class="modal-body">'+body+
                                                '</div>'+
                                                '<div class="modal-footer">'+footer+
                                                        '<button id="cancel" class="btn btn-default" data-dismiss="modal" type="button" name="cancel">Cancelar</button>'+
                                                        '<a id="submit" class="btn btn-danger" href="'+confirmURL+'">Eliminar</a>'+
                                                '</div>'+
										
									'</div>'+
								'</div>'+
                            '</div>';

                                $modal=jQuery(modalString);

                        }

                        $modal.modal('show');
                        return false;
                }

};



</script>

    </body>
</html>
